on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_runtime:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Haxe 4.3.0
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.0

      - name: Checkout
        uses: actions/checkout@v3

      - name: Check Haxe Version
        run: haxe -version

      - name: Test DevEnv.hxml
        run: haxe DevEnv.hxml
